language: node_js
node_js:
- '0.10'
sudo: true
before_install:
- bundle install
# - npm install -g gulp
# - export DISPLAY=:99.0
# - sh -e /etc/init.d/xvfb start
notifications:
  email: false
  slack:
    secure: ft6b+1ugcnFrl6qKNVyQboFBapRI+ci34kGu01O5mMF3WVOlDwJewSKQ2l3TkWrFlt6Ty2nSg8ynMT+iXbudZNPPqoBdKHHFTThu4BoqFoI1DJOSqOO/B7vgAZCgThUX+lqS+rv8pq/XkAi+0LmsBM/U2LLLPR3xaWw0vctP+ykKAU532bAAUZQ086gspMi3ylvqKbXsXqNOWCeKqUADplxuJx4hORV75RN509f6jUDLitaS//2/z117uxoehN52X+orO0TyCIE5OSXL/Zm7HKE4HJp0we+1n7BC3VyXWNlX8yw+e5QA8z9C0hvtqLCpkuEIT61pOM5hYAS5Z8FcOHc9hmqphsZiwL/Nosu25+9e2/XkvNSo9UvZ0VXcePlZQpTe9F/UDjou8ofouPIe7JIUUu19WX/XmK/31ux/bF3/DVbABccPQINMwAy+MZR4iKKBGjUhhcZPTSZDufoUn2u6jR310pbqfxVgPDFx92R5+/pou7ULwmNR46xFO0Xv59T3QR8HnoMnxth1DAu22nWM1ezYflLlp154IdxwyQlIwy46PJ7ZchP7yR+UP7S71Kvv1m7RQ05RXireShhkIykn1IchWgk64HaAWP82wJJvBzbAgC7RUuLfbGS2Q4C2XnvqyLmWtW8Lk55mIrayLYXiNJJss+R1TokywbvLgBM=
script:
- gulp monolith
before_deploy:
- gulp release-zip
deploy:
  - provider: cloudfoundry
    api: https://api.run.pivotal.io
    username: pivotal-ui@pivotal.io
    password:
      secure: gHmcewGbR/rNN8mYej9Sr33fwkcv2eEQ/Bf3rbgsjuRcZH2o9+9j/85BxwGT41NwPfB0wX1I9RC8Gz6SHwFio1IRCR/Y1z/Jzfs1h40JwFzzN1HkFwAxdd5+61pDHOxDl7tqDoqLo5PB820QUiQ0QhZTsWsNhYoX/+u0pO/o/oACFA29wf3QTMyOYGt+ImpMRqQcNwsBHZYPHqc2twmjNLNyH3Zps+RXtnZUWY6FrfcuIbYezsfwdC2Q8pN5hRdIJ1XGLcmZYLYUYgDIAxLcY5/E6Ht6jirCgXjoy3V0Zd3iCuXZnmf9mpAvaDycKK4ZRi63gdbmzzZiPOC2/sbE2Rwk9T6v6Wci9iVJketncYd4r6ofKn0Zvm8ZzP74NuU8pOEpDXGzK+7lEtTYglO3np2gn4HRSzDI/ANirtPzW/EgD3QRkmMu7XcnvUYEusSRjYCGe3P270a2D2t/fDlYV/96Dft/7F9HNhQJVqzlUWqitO7La+kNRrGI9dCSoKUxESbtobTzrb5HG93C0YCegMnsyfJ8yRMq/8Ya9FEQEoqkZRGS6zQPwmOimQl+AuinKC3WxNPUxpfn2A1tjYOouJK+HUumNzsRLvCxQo3bMhyKD5Rx44SVQfungsWA35Zd2hEZ75YJAJ2nJqOnFSf3b71S4OR965je31m+vDMGzXo=
    organization: pivotal
    space: pivotal-ui-staging
    on:
      repo: pivotal-cf/pivotal-ui
      branch: foobar
  - provider: releases
    api_key:
      secure: FEY0UlBt+Rix+8LiEgNXBQUk2Jv2zpKjDCnWjPCVzRhgngDmLmxqmi0NoWqLXQ7LNqXdjVKqqYbhndOL5bJxTPyFG5kqPutVYM79iAXUSFQ3To6U57N4Bv7JeD6u97hWEw9c4VfwyysdPjop1a9ppRik6fuiPd6PBPRpPHeoFTe9azJ009KhFi5O4HGHHjWNRuZluZxoDMrHi5NBYdhxtzxEiG9aIvGgwrO6us+sdhd2CwqTV+mRxi2hmnxkK3myPSuQZWzk0M2CgXE90WwqzgcW9dp4nOKYiFYLcdwE6e9VKJMntNMv9Fy/4yyb7Q48IVoVNu5xD/jsAjydFTnowQhk7qtNjFMlMhJaVnnoflCZ9uF0Q0mXpy80G5QfqP07JRvKz49DSqiG2x1ZM+6hCnNnRg74bis1aKw0TBh2ClV5K6CYHX+b2iXVz2Hkdutlxm0mWRr7mA7GQIQXUaTW3EHXnUSOYFVBvDZSZ0zGnPX2dkQYev2j3nqAsCPl6MvmkesUusIR15GbxMtfJksa3Zrtz/68lML4bvshqHvzeUpser70FifWkA5R4Rpo/PO8b0ddRR7/K7mNovOI60mgwBKKFgEBzBIKBl/1LLrUNOFZdefglgQOHRNi5SGyOzwV2zCs4Yfw6XHRUmgyMKzVdC0VL9c+WOtc5cy7DTRGauk=
    file: pui.zip
    on:
      repo: pivotal-cf/pivotal-ui
      tags: true
