source 'https://rubygems.org'

gem 'hologram', git: 'https://github.com/gpleiss/hologram.git', branch: 'custom_code_example'
# gem 'hologram', path: '../hologram'
gem 'haml'
gem 'sass'
gem 'coffee-script'
gem 'compass', '~> 1.0.1'
gem 'pry'
gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
